"use client";

import { useEffect, useState } from "react";

type Candidate = { id: number; name: string; team: { name: string; color: string | null } | null };
type Round = { id: number; title: string | null; maxBet: number; multiplier: number; maxPlayers: number; candidates: Candidate[]; stake: number; selectedPlayerIds: number[] };
export default function BettingPanel() {
  const [rounds, setRounds] = useState<Round[]>([]); const [message, setMessage] = useState(""); const [stakes, setStakes] = useState<Record<number, string>>({}); const [selections, setSelections] = useState<Record<number, number[]>>({});
  async function load() { const response = await fetch("/api/betting/active", { cache: "no-store" }); if (response.ok) { const data = await response.json(); setRounds(data.rounds); setSelections((current) => Object.fromEntries(data.rounds.map((round: Round) => [round.id, current[round.id] ?? round.selectedPlayerIds]))); setStakes((current) => Object.fromEntries(data.rounds.map((round: Round) => [round.id, current[round.id] ?? String(round.stake || "")] ))); } }
  useEffect(() => { let active = true; void fetch("/api/betting/active", { cache: "no-store" }).then(async (response) => { if (active && response.ok) { const data = await response.json(); setRounds(data.rounds); setSelections(Object.fromEntries(data.rounds.map((round: Round) => [round.id, round.selectedPlayerIds]))); setStakes(Object.fromEntries(data.rounds.map((round: Round) => [round.id, round.stake ? String(round.stake) : ""]))); } }); const interval = window.setInterval(load, 8000); return () => { active = false; window.clearInterval(interval); }; }, []);
  function toggle(round: Round, playerId: number) { setSelections((current) => { const selected = current[round.id] ?? []; if (selected.includes(playerId)) return { ...current, [round.id]: selected.filter((id) => id !== playerId) }; if (selected.length >= round.maxPlayers) return current; return { ...current, [round.id]: [...selected, playerId] }; }); }
  async function submit(round: Round) { const response = await fetch(`/api/betting/${round.id}/bet`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ stake: Number(stakes[round.id]), selectedPlayerIds: selections[round.id] ?? [] }) }); const result = await response.json(); setMessage(response.ok ? `Sázka uložena: ${stakes[round.id]} bodů.` : result.error); if (response.ok) await load(); }
  if (!rounds.length) return null;
  return <section className="betting-panel"><p className="eyebrow"><span /> aktivní sázky</p><h2>Tipni si<br /><i>svého hráče.</i></h2>{rounds.map((round) => <article className="bet-round-card" key={round.id}><h3>{round.title ?? `Sázka #${round.id}`}</h3><p className="betting-reward">Vklad max. <b>{round.maxBet} bodů</b> · výhra vklad × <b>{round.multiplier}</b> · vyber max. {round.maxPlayers}</p><div className="bet-stake-row"><label>Vklad <input type="number" min="1" max={round.maxBet} value={stakes[round.id] ?? ""} onChange={(event) => setStakes({ ...stakes, [round.id]: event.target.value })} /></label><button type="button" onClick={() => void submit(round)}>Vsadit</button></div><div className="bet-candidates">{round.candidates.map((candidate) => <button className={(selections[round.id] ?? []).includes(candidate.id) ? "selected" : ""} key={candidate.id} type="button" onClick={() => toggle(round, candidate.id)}>{candidate.name}<small>{candidate.team?.name ?? "Bez týmu"}</small></button>)}</div></article>)}{message && <p className="task-success">{message}</p>}</section>;
}
