"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
type Post = { id: number; text: string; photoUrl: string | null; isSystem: boolean; player: { name: string } | null };
type Board = { players: { id: number; rank: number; name: string; points: number; team: { color: string | null } | null }[]; teams: { id: number; name: string; points: number; color: string | null }[] };
function postText(text: string) { const q = text.match(/^Otázka:\s*(.*)$/m)?.[1]; const a = text.match(/^Odpověď:\s*(.*)$/m)?.[1]; return q && a ? <><span className="post-question-label">Otázka:</span><strong className="home-question-text">{q}</strong><span className="post-answer-label">Odpověď:</span><strong className="home-answer-text">{a}</strong></> : text; }
export default function Home() {
 const router = useRouter(); const [name,setName]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [posts,setPosts]=useState<Post[]>([]); const [board,setBoard]=useState<Board|null>(null); const [postIndex,setPostIndex]=useState(0);
 async function enterGame(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!name.trim())return;setLoading(true);const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});const result=await response.json();setLoading(false);if(!response.ok){setError(result.error??"Vstup se nepodařil.");return;}router.push("/game");}
 useEffect(()=>{let active=true;const load=async()=>{const [postsResponse,boardResponse]=await Promise.all([fetch("/api/dashboard",{cache:"no-store"}),fetch("/api/leaderboard",{cache:"no-store"})]);if(!active)return;if(postsResponse.ok)setPosts((await postsResponse.json()).posts);if(boardResponse.ok)setBoard(await boardResponse.json());};void load();const interval=window.setInterval(load,10000);return()=>{active=false;window.clearInterval(interval);};},[]);
 useEffect(()=>{if(posts.length<2)return;const interval=window.setInterval(()=>setPostIndex((index)=>(index+1)%posts.length),5000);return()=>window.clearInterval(interval);},[posts.length]);
 const activePost=posts[postIndex];
 return <main className="party-home minimal-home"><nav className="party-nav"><a className="brand" href="#top"><span className="brand-mark">✦</span><span>Survival <em>Party</em></span></a><div className="party-nav-actions"><form className="top-login" onSubmit={enterGame}><input value={name} onChange={(event)=>setName(event.target.value)} placeholder="Tvoje jméno" aria-label="Tvoje jméno"/><button type="submit" disabled={loading}>{loading?"…":"Vstoupit"}</button></form><a className="admin-link" href="/admin">Administrace <span>↗</span></a></div></nav>{error&&<p className="home-error">{error}</p>}<section className="home-dashboard"><div className="home-section-label"><span/> NÁSTĚNKA <small>živě</small></div><div className="animated-post" key={activePost?.id??"empty"}>{activePost?<div className="home-post-layout">{activePost.photoUrl&&<Image className="home-post-photo" src={activePost.photoUrl} alt="Fotka z party" width={900} height={600} unoptimized/>}<div><p className="post-kicker">{activePost.isSystem?"Organizace":activePost.player?.name}</p><div className="home-post-copy">{postText(activePost.text)}</div></div></div>:<><p className="post-kicker">Survival Party</p><h1>Party začíná.<br/><i>Buď u toho.</i></h1></>}</div><div className="post-dots">{posts.slice(0,6).map((post,index)=><button aria-label={`Příspěvek ${index+1}`} className={index===postIndex?"active":""} key={post.id} onClick={()=>setPostIndex(index)}/>)}</div></section><section className="home-leaderboard"><div className="home-section-label"><span/> ŽEBŘÍČEK <small>průběžně</small></div><div className="home-board-grid"><div className="home-board-teams"><h2>Kmeny</h2>{board?.teams.slice(0,5).map((team,index)=><div className="home-board-row" key={team.id}><strong>{String(index+1).padStart(2,"0")}</strong><span className="rank-dot" style={{background:team.color??"#df633d"}}/><b>{team.name}</b><em>{team.points} b.</em></div>)}</div><div className="home-board-players"><h2>Hráči</h2>{board?.players.slice(0,5).map((player)=><div className="home-board-row" key={player.id}><strong>{String(player.rank).padStart(2,"0")}</strong><span className="rank-dot" style={{background:player.team?.color??"#df633d"}}/><b>{player.name}</b><em>{player.points} b.</em></div>)}</div></div></section><footer className="party-footer"><span>Survival Party</span><span>Hra pro přátele · 2026</span></footer></main>;
}
