"use client";

import Image from "next/image";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { compressImage } from "@/lib/compress-image";

type Post = { id: number; text: string; photoUrl: string | null; isSystem: boolean; createdAt: string; player: { name: string } | null };
export default function AdminDashboard() {
  const [posts, setPosts] = useState<Post[]>([]); const [text, setText] = useState(""); const [photoUrl, setPhotoUrl] = useState(""); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false);
  async function load() { const response = await fetch("/api/admin/dashboard", { cache: "no-store" }); if (response.ok) setPosts((await response.json()).posts); }
  useEffect(() => { let active = true; void fetch("/api/admin/dashboard", { cache: "no-store" }).then(async (response) => { if (active && response.ok) setPosts((await response.json()).posts); }); return () => { active = false; }; }, []);
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); const data = new FormData(); data.append("file", await compressImage(file)); const response = await fetch("/api/admin/upload", { method: "POST", body: data }); const result = await response.json().catch(() => ({ error: "Soubor je příliš velký nebo se ho nepodařilo nahrát." })); setUploading(false); setMessage(response.ok ? "Fotka nahrána." : result.error); if (response.ok) setPhotoUrl(result.url); }
  async function publish(event: FormEvent) { event.preventDefault(); if (!photoUrl) { setMessage("Nejdřív nahraj fotku."); return; } const response = await fetch("/api/admin/dashboard", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, photoUrl }) }); setMessage(response.ok ? "Příspěvek zveřejněn." : (await response.json()).error); if (response.ok) { setText(""); setPhotoUrl(""); await load(); } }
  async function remove(id: number) { await fetch(`/api/admin/dashboard/${id}`, { method: "DELETE" }); await load(); }
  return <section className="admin-dashboard"><div className="admin-section-heading"><div><p className="eyebrow"><span /> organizace</p><h2>Nástěnka<br /><i>v pohybu.</i></h2></div><p className="admin-message">{message}</p></div><form className="dashboard-admin-form" onSubmit={publish}><textarea required placeholder="Co se právě děje?" value={text} onChange={(event) => setText(event.target.value)} /><div className="admin-photo-field">{photoUrl && <Image src={photoUrl} alt="Náhled příspěvku" width={120} height={80} unoptimized />}<label>{uploading ? "Nahrávám…" : "Přidat fotku"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} /></label></div><button type="submit" disabled={uploading || !photoUrl}>Zveřejnit příspěvek</button></form><div className="admin-post-list">{posts.map((post) => <article key={post.id}><div>{post.photoUrl && <Image src={post.photoUrl} alt="Fotka příspěvku" width={70} height={50} unoptimized />}<div><b>{post.isSystem ? "Organizace" : post.player?.name}</b><p>{post.text}</p></div></div><button type="button" onClick={() => void remove(post.id)}>Smazat</button></article>)}</div></section>;
}
