"use client";

import { FormEvent, useEffect, useState } from "react";

type Player = { id: number; name: string; teamId: number | null; team?: { name: string; color: string | null } | null };
type Team = { id: number; name: string; players: Player[] };
type Round = { id: number; title: string | null; isOpen: boolean; isResolved: boolean; maxBet: number; multiplier: number; maxPlayers: number; candidates: { playerId: number; player: Player }[] };

export default function AdminBetting() {
  const [teams, setTeams] = useState<Team[]>([]); const [rounds, setRounds] = useState<Round[]>([]); const [candidateIds, setCandidateIds] = useState<string[]>([]); const [winnerIds, setWinnerIds] = useState<Record<number, number[]>>({}); const [title, setTitle] = useState(""); const [maxBet, setMaxBet] = useState("100"); const [multiplier, setMultiplier] = useState("2"); const [maxPlayers, setMaxPlayers] = useState("1"); const [message, setMessage] = useState("");
  const players = teams.flatMap((team) => team.players.map((player) => ({ ...player, team: { name: team.name, color: null } })));
  async function load() { const [teamsResponse, roundsResponse] = await Promise.all([fetch("/api/admin/teams"), fetch("/api/admin/betting")]); if (teamsResponse.ok) setTeams((await teamsResponse.json()).teams); if (roundsResponse.ok) setRounds((await roundsResponse.json()).rounds); }
  useEffect(() => { let active = true; void Promise.all([fetch("/api/admin/teams"), fetch("/api/admin/betting")]).then(async ([teamsResponse, roundsResponse]) => { if (!active) return; if (teamsResponse.ok) setTeams((await teamsResponse.json()).teams); if (roundsResponse.ok) setRounds((await roundsResponse.json()).rounds); }); return () => { active = false; }; }, []);
  async function create(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/betting", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, candidatePlayerIds: candidateIds.map(Number), maxBet: Number(maxBet), multiplier: Number(multiplier), maxPlayers: Number(maxPlayers) }) }); const data = await response.json(); setMessage(response.ok ? "Sázková runda vytvořena." : data.error); if (response.ok) { setTitle(""); setCandidateIds([]); await load(); } }
  async function close(id: number) { await fetch(`/api/admin/betting/${id}/close`, { method: "PATCH" }); await load(); }
  async function resolve(id: number) { const response = await fetch(`/api/admin/betting/${id}/resolve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ winnerPlayerIds: winnerIds[id] ?? [] }) }); setMessage(response.ok ? "Sázky vyhodnoceny a body rozdány." : (await response.json()).error); await load(); }
  function toggleWinner(roundId: number, playerId: number) { setWinnerIds((current) => { const selected = current[roundId] ?? []; return { ...current, [roundId]: selected.includes(playerId) ? selected.filter((id) => id !== playerId) : [...selected, playerId] }; }); }
  return <section className="admin-betting"><div className="admin-section-heading"><div><p className="eyebrow"><span /> sázky</p><h2>Sázková<br /><i>runda.</i></h2></div><p className="admin-message">{message}</p></div><form className="voting-admin-form betting-create-form" onSubmit={create}><input placeholder="Název sázky" value={title} onChange={(event) => setTitle(event.target.value)} /><select multiple value={candidateIds} onChange={(event) => setCandidateIds(Array.from(event.target.selectedOptions, (option) => option.value))}>{players.map((player) => <option key={player.id} value={player.id}>{player.name} · {player.team?.name ?? "Bez týmu"}</option>)}</select><input type="number" min="1" placeholder="Max. vklad" value={maxBet} onChange={(event) => setMaxBet(event.target.value)} /><input type="number" min="1" placeholder="Násobitel" value={multiplier} onChange={(event) => setMultiplier(event.target.value)} /><input type="number" min="1" placeholder="Počet tipů" value={maxPlayers} onChange={(event) => setMaxPlayers(event.target.value)} /><button type="submit">Otevřít sázky</button></form><p className="betting-admin-help">Vyber kandidáty ze všech týmů. Hráč si pak vsadí až do limitu a vybere maximálně nastavený počet kandidátů.</p><div className="admin-voting-list">{rounds.map((round) => <article key={round.id}><div><b>{round.title ?? `Sázka #${round.id}`}</b><small>Max. {round.maxBet} bodů · ×{round.multiplier} · až {round.maxPlayers} hráčů · {round.isResolved ? "Vyhodnoceno" : round.isOpen ? "Otevřené" : "Uzavřené"}</small><div className="round-candidate-list">{round.candidates.map((candidate) => <span key={candidate.playerId}>{candidate.player.name} · {candidate.player.team?.name ?? "Bez týmu"}</span>)}</div>{!round.isOpen && !round.isResolved && <div className="winner-picker">{round.candidates.map((candidate) => <label key={candidate.playerId}><input type="checkbox" checked={(winnerIds[round.id] ?? []).includes(candidate.playerId)} onChange={() => toggleWinner(round.id, candidate.playerId)} /> {candidate.player.name}</label>)}<button type="button" onClick={() => void resolve(round.id)}>Vyhodnotit sázky</button></div>}</div>{round.isOpen && <button type="button" onClick={() => void close(round.id)}>Uzavřít sázky</button>}</article>)}</div></section>;
}
