"use client";

import { FormEvent, useEffect, useState } from "react";

type Player = { id: number; name: string; teamId: number | null };
type Team = { id: number; name: string; players: Player[] };
type Question = { id: number; text: string; points: number; scope: string; isActive: boolean; _count: { answers: number } };

export default function AdminQuestions() {
  const [teams, setTeams] = useState<Team[]>([]); const [players, setPlayers] = useState<Player[]>([]); const [questions, setQuestions] = useState<Question[]>([]); const [text, setText] = useState(""); const [points, setPoints] = useState("10"); const [scope, setScope] = useState("ALL"); const [teamId, setTeamId] = useState(""); const [playerIds, setPlayerIds] = useState<string[]>([]); const [message, setMessage] = useState("");
  async function load() { const [teamResponse, questionResponse] = await Promise.all([fetch("/api/admin/teams"), fetch("/api/admin/questions")]); if (teamResponse.ok) { const data = await teamResponse.json(); setTeams(data.teams); setPlayers(data.players); } if (questionResponse.ok) setQuestions((await questionResponse.json()).questions); }
  useEffect(() => { let active = true; void Promise.all([fetch("/api/admin/teams"), fetch("/api/admin/questions")]).then(async ([teamResponse, questionResponse]) => { if (!active) return; if (teamResponse.ok) { const data = await teamResponse.json(); setTeams(data.teams); setPlayers(data.players); } if (questionResponse.ok) setQuestions((await questionResponse.json()).questions); }); return () => { active = false; }; }, []);
  async function create(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/questions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, points: Number(points), scope, teamId: Number(teamId), playerIds: playerIds.map(Number) }) }); const data = await response.json(); setMessage(response.ok ? "Otázka vytvořena." : data.error); if (response.ok) { setText(""); setPlayerIds([]); await load(); } }
  async function close(id: number) { await fetch(`/api/admin/questions/${id}`, { method: "PATCH" }); await load(); }
  return <section className="admin-questions"><div className="admin-section-heading"><div><p className="eyebrow"><span /> otázky pro hráče</p><h2>Otázky<br /><i>v partě.</i></h2></div><p className="admin-message">{message}</p></div><form className="voting-admin-form question-create-form" onSubmit={create}><textarea placeholder="Napiš otázku pro hráče" value={text} onChange={(event) => setText(event.target.value)} /><input type="number" min="0" placeholder="Odměna" value={points} onChange={(event) => setPoints(event.target.value)} /><select value={scope} onChange={(event) => setScope(event.target.value)}><option value="ALL">Všichni hráči</option><option value="TEAM">Celý tým</option><option value="CUSTOM_GROUP">Vybraní hráči</option></select>{scope === "TEAM" && <select value={teamId} onChange={(event) => setTeamId(event.target.value)}><option value="">Vyber tým</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select>}{scope === "CUSTOM_GROUP" && <select multiple value={playerIds} onChange={(event) => setPlayerIds(Array.from(event.target.selectedOptions, (option) => option.value))}>{players.map((player) => <option key={player.id} value={player.id}>{player.name} · {teams.find((team) => team.id === player.teamId)?.name ?? "Bez týmu"}</option>)}</select>}<button type="submit">Vytvořit otázku</button></form><div className="admin-voting-list">{questions.map((question) => <article key={question.id}><div><b>{question.text}</b><small>+{question.points} bodů · {question.scope} · {question._count.answers} odpovědí</small></div>{question.isActive && <button type="button" onClick={() => void close(question.id)}>Uzavřít otázku</button>}</article>)}</div></section>;
}
