"use client";

import { FormEvent, useEffect, useState } from "react";

type Team = { id: number; name: string; players: { id: number; name: string }[] };
type Round = { id: number; title: string | null; isOpen: boolean; isResolved: boolean; rewardPoints: number; teamA: { name: string }; teamB: { name: string }; candidates: { playerId: number; player: { name: string } }[] };
export default function AdminBetting() {
  const [teams, setTeams] = useState<Team[]>([]); const [rounds, setRounds] = useState<Round[]>([]); const [teamA, setTeamA] = useState(""); const [teamB, setTeamB] = useState(""); const [candidateIds, setCandidateIds] = useState<string[]>([]); const [winnerIds, setWinnerIds] = useState<Record<number, number[]>>({}); const [title, setTitle] = useState(""); const [reward, setReward] = useState("20"); const [message, setMessage] = useState("");
  async function load() { const [teamsResponse, roundsResponse] = await Promise.all([fetch("/api/admin/teams"), fetch("/api/admin/betting")]); if (teamsResponse.ok) setTeams((await teamsResponse.json()).teams); if (roundsResponse.ok) setRounds((await roundsResponse.json()).rounds); }
  useEffect(() => { let active = true; void Promise.all([fetch("/api/admin/teams"), fetch("/api/admin/betting")]).then(async ([teamsResponse, roundsResponse]) => { if (!active) return; if (teamsResponse.ok) setTeams((await teamsResponse.json()).teams); if (roundsResponse.ok) setRounds((await roundsResponse.json()).rounds); }); return () => { active = false; }; }, []);
  const candidates = teams.filter((team) => String(team.id) === teamA || String(team.id) === teamB).flatMap((team) => team.players);
  async function create(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/betting", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, teamAId: Number(teamA), teamBId: Number(teamB), candidatePlayerIds: candidateIds.map(Number), rewardPoints: Number(reward) }) }); setMessage(response.ok ? "Sázková runda vytvořena." : (await response.json()).error); if (response.ok) { setCandidateIds([]); await load(); } }
  async function close(id: number) { await fetch(`/api/admin/betting/${id}/close`, { method: "PATCH" }); await load(); }
  async function resolve(id: number) { const response = await fetch(`/api/admin/betting/${id}/resolve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ winnerPlayerIds: winnerIds[id] ?? [] }) }); setMessage(response.ok ? "Sázky vyhodnoceny a body rozdány." : (await response.json()).error); await load(); }
  function toggleWinner(roundId: number, playerId: number) { setWinnerIds((current) => { const selected = current[roundId] ?? []; return { ...current, [roundId]: selected.includes(playerId) ? selected.filter((id) => id !== playerId) : [...selected, playerId] }; }); }
  return <section className="admin-betting"><div className="admin-section-heading"><div><p className="eyebrow"><span /> výzva mezi kmeny</p><h2>Sázková<br /><i>runda.</i></h2></div><p className="admin-message">{message}</p></div><form className="voting-admin-form" onSubmit={create}><input placeholder="Název rundy" value={title} onChange={(event) => setTitle(event.target.value)} /><select value={teamA} onChange={(event) => setTeamA(event.target.value)}><option value="">Tým A</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><select value={teamB} onChange={(event) => setTeamB(event.target.value)}><option value="">Tým B</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><select multiple value={candidateIds} onChange={(event) => setCandidateIds(Array.from(event.target.selectedOptions, (option) => option.value))}>{candidates.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</select><input type="number" min="1" value={reward} onChange={(event) => setReward(event.target.value)} /><button type="submit">Otevřít sázky</button></form><div className="admin-voting-list">{rounds.map((round) => <article key={round.id}><div><b>{round.title ?? `${round.teamA.name} vs. ${round.teamB.name}`}</b><small>{round.rewardPoints} bodů · {round.isResolved ? "Vyhodnoceno" : round.isOpen ? "Otevřené" : "Uzavřené"}</small>{!round.isOpen && !round.isResolved && <div className="winner-picker">{round.candidates.map((candidate) => <label key={candidate.playerId}><input type="checkbox" checked={(winnerIds[round.id] ?? []).includes(candidate.playerId)} onChange={() => toggleWinner(round.id, candidate.playerId)} /> {candidate.player.name}</label>)}<button type="button" onClick={() => void resolve(round.id)}>Vyhodnotit sázky</button></div>}</div>{round.isOpen && <button type="button" onClick={() => void close(round.id)}>Uzavřít sázky</button>}</article>)}</div></section>;
}
